sudo: false
dist: trusty
env:
  global:
    - CC_TEST_REPORTER_ID=3e591ac755b74f28951c0926d3255589a814fe5fbceadc3f6fafbb74c237cf93
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      npm install codecov
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
