sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
install:
  - npm install
script:
  - npm run coverage
before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi
after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      npm install codecov
      cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov
    fi
