ignore:
  - docs/**/*
  - dist/**/*
  - src/components/browsable-content
  - src/components/content
  - src/components/expr
  - src/components/formal-notation
  - src/components/structure-of-a-compiler
  - src/components/*.js
  - src/modules/antlr/*
  - src/store/modules/*
  - test/**/*.js
