version: 2

defaults: &defaults
  environment:    
    CC_TEST_REPORTER_ID: 3e591ac755b74f28951c0926d3255589a814fe5fbceadc3f6fafbb74c237cf93
  docker:
    - image: circleci/node:8-browsers
  working_directory: ~/project/json-editor

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0.0.1-json-editor-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v0.0.1-json-editor-{{ .Branch }}-
            - v0.0.1-json-editor-
      - run:
          name: Install dependencies
          command: |
            npm install && npm rebuild node-sass
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          key: v0.0.1-json-editor-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - json-editor

  run-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run coverage
          command: |
            npm run coverage
      - run:
          name: Send coverage report to Code Climate
          command: |
            ./cc-test-reporter after-build --exit-code $?
      - run:
          name: Send coverage report to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  install-and-run-tests:
    jobs:
      - install
      - run-tests:
          requires:
            - install
