version: 2

defaults: &defaults
  working_directory: ~/project/json-editor
  docker:
    - image: circleci/node:10-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - json-editor-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - json-editor-{{ .Branch }}-
            - json-editor-
      - run: npm install && npm rebuild node-sass && npm -g codecov
      - save_cache:
          key: json-editor-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - json-editor

  test-cover:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run coverage && codecov

workflows:
  version: 2
  install-and-coverage:
    jobs:
      - install
      - test-cover:
          requires:
            - install
